### ISSUE TITLE
How to construct a `PacketReader` for constructing an `inside_ogg::OggStreamReader`?

### ISSUE THREAD

**Issue by mitchmindtree** [est31/lewton#13]
The examples seems to [pass a file directly to the `OggStreamReader::new` function](https://github.com/est31/lewton/blob/master/examples/player.rs#L33), however [the docs specify](https://docs.rs/lewton/0.4.1/lewton/inside_ogg/struct.OggStreamReader.html#method.new) that the constructor takes a `PacketReader<T>`. It seems there is no publicly exposed method of constructing a `PacketReader` without importing the `ogg` extern crate, which requires the user to find the current compatible version. It would be nice if `lewton` re-exported the `ogg` crate so that users could access what they needed via `lewton::ogg` - it seems this might also remove the need for the `inside_ogg` module also?

**Comment by est31** [comment]
Hi!

In fact, commit e1e5d9fd820b2ebaa2e8a3ba87f5521967b3e7f6 enables you to construct an  `OggStreamReader` without needing the `ogg` crate yourself. The inconsistency between github master and the docs of the 0.4.1 release comes from this. You can see [here](https://github.com/est31/lewton/blob/0.4.1/examples/player.rs#L35) how the old interface worked.

As it is a breaking API change, I want to wait for further changes I want to do until I release a version `0.5`, but eventually the change will be available to you!

If you want to use the change before the 0.5 release, (which might take some time before its ready), you can specify cargo to [make a git dependency](http://doc.crates.io/specifying-dependencies.html#specifying-dependencies-from-git-repositories) for your crate, but note, you can't upload to crates.io if you have git dependencies. Contact me if you want to upload to crates.io and use the change, we can find a solution in this case.

I want to have the `inside_ogg` module as convenience module so that you can easier use the crate, with a more stable, simple, and smaller interface. Re-exporting the ogg crate instead won't give the simplicity and ease required, and it limits you to specify custom features to the ogg crate, like for async operation.

As commit e1e5d9fd820b2ebaa2e8a3ba87f5521967b3e7f6 fixed this issue, I'm closing it.

**Comment by mitchmindtree** [comment]
Ahh my apologies, I should have checked master in more detail first!

> Contact me if you want to upload to crates.io and use the change, we can find a solution in this case.

I'm currently doing some experiments with designing a multi-format, audio crate, similar in functionality to the PistonDevelopers/image crate but for audio. The idea is to only support pure-rust encoders and decoders and I'm hoping to use lewton for Ogg Vorbis support. It will likely remain a private experiment for a little while yet so no need to rush 0.5 :+1:

> I want to have the `inside_ogg` module as convenience module so that you can easier use the crate, with a more stable, simple, and smaller interface.

This sounds totally reasonable! My only suggestion would be to rename the `inside_ogg` module to `ogg` as the module contains ogg-specific functionality and seeing as you are already omitting the ogg crate itself from the API for simplicity there is no need to indicate that the functionality comes from "inside" the ogg crate (I'm guessing that's what the `inside` in `inside_ogg` indicates?). Feel free to disregard this of course! Just my two cents after `inside_ogg` felt a little awkward.

Thanks for the crate btw! Looking forward to using it in a personal little pure-rust music player app soon :)

**Comment by est31** [comment]
> The idea is to only support pure-rust encoders and decoders

I have considered creating such a project myself (namely, improving [rust-media](https://github.com/pcwalton/rust-media) to a state into it can serve as such a library), but was busy with other things. I support it in any case! Optimally, there could be a shared github organisation for audio decoder/encoder crates which could optionally provide hosting and general organisation. Had you something in mind? I'd love to join!

The "inside" from `inside_ogg` comes from "vorbis inside the Ogg container format". There is generally lots of confusion about what ogg is and what vorbis is, and naming `ogg/vorbis` files `.ogg` (while `ogg/opus` files are named `.opus`) doesn't help...

**Comment by est31** [comment]
See also https://github.com/tomaka/rodio https://github.com/rust-av/rust-av (the second one is LGPL licensed, which is not good for a media library I think...)

Sadly, there is some missing coordination in the (pure) rust media decoding landscape...

**Comment by mitchmindtree** [comment]
> I have considered creating such a project myself ... but was busy with other things

This has also been the case for myself over the past 3 years - I get the feeling most rusty audio devs have had this deep within their todo-lists at some point 😆 

> Optimally, there could be a shared github organisation for audio decoder/encoder crates which could optionally provide hosting and general organisation.

I'm certainly open to this! I started [RustAudio](https://github.com/RustAudio) a little while back in the hopes of bringing the efforts of rusty audio devs together, though the organisation might be a little too general for what you have in mind? Perhaps a new org specifically for encoders and decoders would make more sense? I don't think organisations are always necessary for bringing together concerted effort (tomaka's crates are a good example of this) though it could be useful for making coordination a little easier.

> See also https://github.com/tomaka/rodio

Totally, I was planning to use tomaka/cpal for the examples, but perhaps rodio might be a better fit as it's a little higher level? I haven't had a close look at it just yet, but will do soon. Either way, any excuse to guide more work towards CPAL is useful in my books 😸 I agree wrt licensing by the way - I like the idea of matching Rust's own licensing where possible (e.g. "MIT or Apache-2 at your option") in this case.

**Comment by mitchmindtree** [comment]
By the way, I'll be sure to ping you once I get a rough version of the crate on Github as I'd definitely appreciate your thoughts and input on the API, direction, etc :+1:

**Comment by est31** [comment]
@mitchmindtree replied to you via IRC PM (you are `mindtree` on the mozilla network, right?).
